# Generated by Django 6.0.1 on 2026-02-03 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='outletUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='outlet_banners/')),
                ('banner_active', models.BooleanField(default=True)),
                ('theme_color', models.CharField(default='#0d6efd', max_length=30)),
                ('layout_type', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal')], default='classic', max_length=20)),
                ('Outlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_ui', to='accounts.outlet')),
            ],
        ),
    ]
