# Generated by Django 6.0.1 on 2026-02-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_outletui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletui',
            name='Outlet',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.category')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.outlet')),
            ],
        ),
        migrations.AddField(
            model_name='outletui',
            name='outlet',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_ui', to='accounts.outlet'),
            preserve_default=False,
        ),
    ]
