# Generated by Django 6.0.1 on 2026-02-08 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_outletui_outlet_category_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='manager',
            field=models.OneToOneField(limit_choices_to={'is_outlet_head': True}, on_delete=django.db.models.deletion.CASCADE, related_name='outlet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outletui',
            name='outlet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui', to='accounts.outlet'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('outlet', 'name')},
        ),
    ]
