# Generated by Django 6.0.3 on 2026-03-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order_total_amount_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletui',
            name='banner2',
            field=models.ImageField(blank=True, null=True, upload_to='outlet_banners/'),
        ),
        migrations.AddField(
            model_name='outletui',
            name='banner3',
            field=models.ImageField(blank=True, null=True, upload_to='outlet_banners/'),
        ),
    ]
