# Generated by Django 6.0.3 on 2026-03-25 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_outletui_banner2_outletui_banner3'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_date', models.DateField()),
                ('token_no', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='accounts.order')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='accounts.outlet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['outlet', 'token_date'], name='accounts_or_outlet__8ee99f_idx'), models.Index(fields=['user', 'token_date'], name='accounts_or_user_id_88762d_idx')],
                'constraints': [models.UniqueConstraint(fields=('outlet', 'token_date', 'token_no'), name='unique_outlet_token_per_day')],
            },
        ),
    ]
