# Generated by Django 6.0.3 on 2026-04-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_order_payment_status_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('outlet', 'Outlet Head')], max_length=20, null=True),
        ),
    ]
