# Generated by Django 6.0.3 on 2026-07-24 12:37

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_order_cancelled_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingVerificationUser',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Verification User',
                'verbose_name_plural': 'Pending Verification Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedCustomer',
            fields=[
            ],
            options={
                'verbose_name': 'Verified Customer',
                'verbose_name_plural': 'Verified Customers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
