# Generated by Django 6.0.3 on 2026-08-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url_str',
            field=models.TextField(blank=True, null=True),
        ),
    ]
