# Generated by Django 6.0.3 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_product_image_url_str'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='order_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['outlet', 'status', 'created_at'], name='order_outlet_st_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['outlet', 'status', 'completed_at'], name='order_outlet_st_cmp_idx'),
        ),
    ]
