# Generated by Django 6.0.3 on 2026-09-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='is_accepting_orders',
            field=models.BooleanField(default=True),
        ),
    ]
