# Generated by Django 6.0.3 on 2026-09-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_outlet_is_accepting_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_prep_time_mins', models.PositiveIntegerField(default=20, help_text='Default preparation time in minutes for orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.outlet')),
            ],
        ),
    ]
