# Generated by Django 6.0.3 on 2026-09-18 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_outletsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_job', to='accounts.order')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='accounts.outlet')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='printjob_st_crt_idx')],
            },
        ),
    ]
