# Generated by Django 6.0.3 on 2026-09-23 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_printjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Anonymous', max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1 to 5 stars')),
                ('review_text', models.TextField(blank=True, help_text='Optional customer review', null=True)),
                ('suggestion_text', models.TextField(blank=True, help_text='Optional customer suggestion', null=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Approved by admin to display on reviews page')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Review & Feedback',
                'verbose_name_plural': 'Site Reviews & Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
